# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
GMAIL_USERNAME: Your_Username
GMAIL_PASSWORD: Your_Password
ADMIN_FIRST_NAME: First
ADMIN_LAST_NAME: User
ADMIN_EMAIL: user@example.com
ADMIN_PASSWORD: changeme
ROLES: [admin, silver, gold, platinum]
RECURLY_API_KEY: replace_with_your_recurly_api_key
RECURLY_JS_PRIVATE_KEY: replace_with_your_recurly_js_private_key
RECURLY_SUBDOMAIN: myapp

